name = "ParallelKDE"
uuid = "251f600b-d60c-4092-b1b9-465b74160c73"
authors = ["Christian Sustay (christian.sustay@tum.de)"]
version = "0.1.0"

[compat]
julia = "1.11"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
